In [3]:
import pandas as pd

In [4]:
path = 'data/GDSC2_fitted_dose_response_25Feb20.csv'

In [5]:
df = pd.read_csv(path)
df.head()

  CELL_LINE_NAME       DRUG_NAME   LN_IC50
0        HCC1954  5-Fluorouracil  5.530934
1        HCC1143  5-Fluorouracil  5.747062
2        HCC1187  5-Fluorouracil  6.699858
3        HCC1395  5-Fluorouracil  5.841372
4        HCC1599  5-Fluorouracil  5.503561

In [21]:
cleaned_table = pd.pivot_table(df, columns="DRUG_NAME", index="CELL_LINE_NAME", values="LN_IC50")

In [22]:
clean_df = pd.DataFrame(cleaned_table)
clean_df.head()

DRUG_NAME,5-Fluorouracil,ABT737,AGI-5198,AGI-6780,AMG-319,AT13148,AZ6102,AZ960,AZD1208,AZD1332,...,Vorinostat,WEHI-539,WIKI4,WZ4003,Wee1 Inhibitor,Wnt-C59,XAV939,YK-4-279,ZM447439,Zoledronate
CELL_LINE_NAME,,,,,,,,,,,,,,,,,,,,,
22RV1,2.478859,3.748055,5.893052,3.901068,6.069160,2.378729,2.771439,3.842732,5.003845,3.422703,...,0.846758,4.335838,4.581114,4.000959,2.597779,3.910612,4.825634,2.638076,NaN,3.745340
23132-87,2.168003,3.051137,5.095888,5.168499,4.618705,1.398445,2.029025,1.526864,4.671017,1.930872,...,0.866942,3.996362,3.841691,3.440264,1.797640,5.266275,4.182666,1.911579,NaN,3.594734
42-MG-BA,3.362543,3.022940,4.680624,4.800641,5.247738,3.004648,2.475681,1.071731,5.150479,2.004515,...,1.804640,4.043738,3.687273,3.853185,2.966137,4.574813,3.916266,1.723414,NaN,3.555334
5637,3.313258,2.631881,4.544496,4.682486,4.969635,5.427145,2.328566,2.147739,5.660901,2.716121,...,1.434107,2.845200,3.536451,4.488451,1.926655,4.366879,5.424404,0.082844,NaN,4.148671
639-V,4.410077,4.331129,3.874526,3.606083,4.519618,5.290583,2.594762,1.960404,5.307510,1.709686,...,2.687246,3.929314,3.719778,4.782340,1.848327,4.501633,4.137965,1.517745,NaN,3.031908

In [23]:
clean_df.to_csv('cleaned.csv')